Net6
loic-sharma/BaGet pull request #775
Opened 2023-07-05 05:36 UTC by sunny1028

主版本升级为.NET7
并且升级了绝大部分相关依赖版本
目前为止运行状态良好

如果需要可以自行构建Releases

Addresses https://github.com/loic-sharma/BaGet/issues/761

2023-07-28 11:08 UTC, jkone27 commented
yes pls NET6 LTS

2023-08-11 08:28 UTC, Regenhardt requested changes

2023-08-11 08:28 UTC, Regenhardt commented on src/BaGet.Aliyun/BaGet.Aliyun.csproj
> +    <LangVersion>10.0</LangVersion>
Isn't the langversion coupled to the framework now anyway, do we really need this?

2023-08-11 08:28 UTC, Regenhardt commented on src/BaGet.Aliyun/BaGet.Aliyun.csproj
> +    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="1.1.1" />
Have you tested this in a docker container? I recall sourcelink being complicated when trying to put it in a docker container. Also do we really need sourcelink for something that is mainly a standalone application?

2023-08-11 08:28 UTC, Regenhardt commented on src/BaGet/appsettings.json
> +  //      "Url": "http://*:11050"
It's nice with the asterisk, but why port 11050?

2023-08-12 12:08 UTC, Regenhardt commented on BaGet.sln
> -Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "BaGet.Core.Tests", "tests\BaGet.Core.Tests\BaGet.Core.Tests.csproj", "{89AB1AE2-6CAA-4809-8B74-D78CBE00B049}"
No more tests?

2023-08-17 19:05 UTC, joestr commented
After enabling the tests I get following error:
`The UTC time represented when the offset is applied must be between year 0 and 10,000`

I fixed it by Replacing occourances of `DateTime` with `DateTimeOffset`

2023-08-18 12:23 UTC, Regenhardt commented
The only way I can imagine this error happening is if there's a datetime of 0001-01-01 and then the offset pushes it below that date. I'm kinda sick today so I won't check now, but if you push it with tests enabled I can checkout your branch tomorrow and see if I can find something causing that. I don't think there should be a datetime of 0001-01-01 anywhere so this might be important.

2023-08-31 11:24 UTC, joestr commented
I just had time to publish the changes again @Regenhardt. They are [here](https://github.com/joestr/BaGet-net6-pr-fix/tree/net6)

2023-09-18 10:02 UTC, joestr commented
Fixed the last Unit Test in #786

2026-04-19 15:10 UTC, closed without merging